### ISSUE TITLE
Not working on NodeMCU 0.9 ESP 12

### ISSUE THREAD

**Issue by astaykov** [Azure/azure-iot-arduino-protocol-mqtt#1]
The MQTT version of the samples and implementation is not working at all on NodeMCU 0.9 ESP12.
Tried with both Boards versions 2.2.0 and 2.3.0 under Arduino IDE 1.6.12.
Version of Azure IoT Arduino 1.0.17.
MQTT Sample open directly from the Samples section in Arduino IDE.

The result log in Serial Monitor is:

> ip:192.168.3.105,mask:255.255.255.0,gw:192.168.3.1
> Connected to wifi.
> 
> please start sntp first !
> Fetching NTP epoch time failed! Waiting 2 seconds to retry.
> Tue Dec 20 13:20:39 2016
> 
> Fetched NTP epoch time is: 1482240040
> IoT Hub SDK for C, version 1.0.17
> IoTHubClient accepted the message for delivery
TLS failed to start the connection process.
> Error: io_open failed
> failure connecting to address ih-demos.azure-devices.net:0.
> Evaluated delay 0 at 1 attempt to retry
> 
> TLS failed to start the connection process.
> Error: io_open failed
> failure connecting to address ih-demos.azure-devices.net:0.
> Evaluated delay 0 at 2 attempt to retry
> 
> TLS failed to start the connection process.
> Error: io_open failed
> failure connecting to address ih-demos.azure-devices.net:0.
> Evaluated delay 1 at 3 attempt to retry
> 
> TLS failed to start the connection process.
> Error: io_open failed
> failure connecting to address ih-demos.azure-devices.net:0.

What is more concerning, the line:

> IoTHubClient

 accepted the message for delivery

Is generated from that part of the code:

> if (IoTHubClient_LL_SendEventAsync(iotHubClientHandle, messageHandle, sendCallback, (void*)1) != IOTHUB_CLIENT_OK)
>                                    {
>                                        printf("failed to hand over the message to IoTHubClient");
>                                    }
>                                    else
>                                    {
>                                        printf("IoTHubClient accepted the message for delivery\r\n");
>                                    }

But the message never got to the IoT Hub. It was not actually sent.

**Comment by gsamant** [comment]
Hi, I am facing the same issue. Let me know if you find any workaround

**Comment by mamokarz** [comment]
Hi, sorry about the delay to answer it.

io-open failed means that the IoT Hub is not happy with the connection string that you provided on the `simplesample_mqtt.c`.

```c
static const char* connectionString = "[device connection string]";
```

Can you please check it?

Thanks

**Comment by astaykov** [comment]
Thanks for replying.
Nope. Double and triple checked. Same connection string works perfectly fine with HTTP Protocol.

When trying the MQTT it still gives this cycle:


```
dhcp client start...
ip:192.168.3.100,mask:255.255.255.0,gw:192.168.3.1
Connected to wifi
please start sntp first !
Fetching NTP epoch time failed! Waiting 2 seconds to retry.
Wed Jan 04 20:32:43 2017

Fetched NTP epoch time is: 1483561964
IoT Hub SDK for C, version 1.0.17
IoTHubClient accepted the message for delivery.
TLS failed to start the connection process.
Error: io_open failed
failure connecting to address ih-demos.azure-devices.net:0.
Evaluated delay 0 at 1 attempt to retry

TLS failed to start the connection process.
Error: io_open failed
failure connecting to address ih-demos.azure-devices.net:0.
Evaluated delay 0 at 2 attempt to retry

TLS failed to start the connection process.
Error: io_open failed
failure connecting to address ih-demos.azure-devices.net:0.
Evaluated delay 1 at 3 attempt to retry

TLS failed to start the connection process.
Error: io_open failed
failure connecting to address ih-demos.azure-devices.net:0.
Evaluated delay 5 at 4 attempt to retry

TLS failed to start the connection process.
Error: io_open failed
failure connecting to address ih-demos.azure-devices.net:0.
Evaluated delay 11 at 5 attempt to retry

Evaluated delay 8 at 5 attempt to retry

Evaluated delay 13 at 5 attempt to retry

```
I can provide a Device Connection string (and Arduino Project) for test via PM.
Just to exclude Firewall issues I just tried the following command on the same WiFi network as the device which resulted in successful connection:

> telnet  ih-demos.azure-devices.net 8883

I was able to connect to the IoT Hub over port 8883 - for secure MQTT.

P.S. Created new Device identity just to be 100% sure that I do not mess with existing and possibly faulty identities.

**Comment by mamokarz** [comment]
8883 is the right port. So, what is not clear to me is why the SDK is trying to connect to the port 0.

```
failure connecting to address ih-demos.azure-devices.net:0.
```

In the azure IoT SDK, you will find the port number hardcoded in `iothubtransportmqtt.c`.

```c
        TLSIO_CONFIG tls_io_config;
        tls_io_config.hostname = fqdn;
        tls_io_config.port = 8883;
        /* Codes_SRS_IOTHUB_MQTT_TRANSPORT_07_012: [ getIoTransportProvider shall return the XIO_HANDLE returns by xio_create. ] */
        result = xio_create(io_interface_description, &tls_io_config);
```

The `xio_create` for Arduino calls the file `tlsio_arduino.c` in the AzureIoTUtility library, which stores the URL and the port in the tlsio_instance. When the SDK tries to open the connection, this information is forward to the sslClient.

```c
            else if (sslClient_connect(tlsio_instance->remote_addr, tlsio_instance->port))
``` 

Can you please investigate if at this point the port number is correct or not?

-Thanks

**Comment by astaykov** [comment]
Hi,
I am clueless.
I tried to inject some Log in various places and this is what I got:

> iothubtransport_mqtt_common.c :: InitializeConnection transport_data->portNum: 0
> iothubtransport_mqtt_common.c :: SendMqttConnectMsg transport_data->portNum: 0
> Something happens in tlsio_arduino.c: tlsio_instance->port: 8883 and tlsio_config->port: 8883
> tlsio_arduino tlsio_instance->remote_addr: 734020877, tlsio_instance->port: 8883
> TLS failed to start the connection process.

Now - why the portNum is 0 in the iothubtransport_mqtt_common.c and has the value of 8883 in tlsio_arduino.c - probably because it is later hard-coded/set to the 8883 value. I assume the connection is correctly tried on port 8883 but the log message is wrong, because portNum is set on a later stage of the process.
Without being C/C++ Expert I see that the remote_addr is (should be?) correct, as the 734020877 translates, if I am not mistaken to 13.69.192.43, which is exactly the IP address that my DNSes resolve for the ih-demos.azure-devices.net.

As a last resort, I even tried changing the SendMqttConnectMsg method and explicitly set the portNum property of the transport_data object:
```

static int SendMqttConnectMsg(PMQTTTRANSPORT_HANDLE_DATA transport_data)
{
    int result;
	LogError("iothubtransport_mqtt_common :: SendMqttConnectMsg transport_data->portNum: %d", transport_data->portNum);
	transport_data->portNum = 8883;
	LogError("iothubtransport_mqtt_common :: SendMqttConnectMsg transport_data->portNum: %d", transport_data->portNum);

```
which only fixed the log message, but not the overall workflow:

> othubtransport_mqtt_common.c :: InitializeConnection transport_data->portNum: 0
> iothubtransport_mqtt_common :: SendMqttConnectMsg transport_data->portNum: 0
> iothubtransport_mqtt_common :: SendMqttConnectMsg transport_data->portNum: 8883
> Something happens in tlsio_arduino.c: tlsio_instance->port: 8883 and tlsio_config->port: 8883
> tlsio_arduino &tlsio_instance->remote_addr: 1073697108, &tlsio_instance->port: 1073697112
> tlsio_arduino tlsio_instance->remote_addr: 734020877, tlsio_instance->port: 8883
> TLS failed to start the connection process.
> result != 0 and we call on_io_open_complete
> result != 0 and we call on_io_error
> Error: io_open failed
> failure connecting to address ih-demos.azure-devices.net:8883.
> iothubtransport_mqtt_common.c :: InitializeConnection transport_data->portNum: 8883
> Evaluated delay 0 at 1 attempt to retry

;(

P.S. Explicitly setting portNum in the InitializeConnection() method does not change anything either...

And again, the commandline 

> telnet 13.69.192.43 8883

executed from the same WiFi network as the device works just fine and I am able to establish connection between my network and the IoT Hub on port 8883.

P.S. The device is definitely trying to establish connection on the correct IP Address with the correct Port. What I did for dirty test is - configured routing on my WiFi router to send all packets with destination address 13.69.192.43 to my computer. On my computer used WireShark and confirm that the ESP8266 tries to establish connection with that IP address on port 8883. However I cannot debug further, because of the closed loop for this destination IP Address - Router sends packets to my PC, my PC tries to establish connection via the router and the packets are again back to my PC. But this at least proved that the device has correct address and port numbers...

**Comment by jorupp** [comment]
It's possible this is related to https://github.com/Azure-Samples/iot-hub-c-m0wifi-getstartedkit/issues/44 - the Feather M0 doesn't seem to work on MQTT either, but works on HTTP.

Could this be an issue with these devices (ESP8266 and ATWINC1500) supporting the version of TLS needed for the HTTP endpoint, but not for the MQTT endpoint?

**Comment by mamokarz** [comment]
Hi jorupp, I’m still investigating what is the issue here, but we expected that MQTT works as fine as HTTP.

**Comment by mamokarz** [comment]
Hi astaykov, take a further investigation, the `iothubtransport_mqtt_common.c` do not have the port number, the `iothubtransportmqtt.c` send this information directly to the `tlsio_arduino` in the `getIoTransportProvider` function (calling xio_create). So, try to print the port number in the iothubtransport_mqtt_common is a mistake, and that is why the error log shows the port number as 0 besides the correct 8886. I’m sorry that we expended time investigating it.

The good news is, the MQTT code can generate some communication logs, we just need to activate it. Can you please change the `simplesample_mqtt.c` to enable this logs?

To do that you need set this option on the IoTHubClient_LL. Localize the `IoTHubClient_LL_CreateFromConnectionString` on `simplesample_mqtt.c`, and add the `traceOn` option after that, as follow.

```c
IOTHUB_CLIENT_LL_HANDLE iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString, MQTT_Protocol);
            
bool traceOn = true;
IoTHubClient_LL_SetOption(iotHubClientHandle, "logtrace", &traceOn);
```

**Comment by astaykov** [comment]
Can it get weirder?

I did what you say:

```
            IOTHUB_CLIENT_LL_HANDLE iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString, MQTT_Protocol);
            
            bool traceOn = true;
            IOTHUB_CLIENT_RESULT result = IoTHubClient_LL_SetOption(iotHubClientHandle, "logtrace", &traceOn);
            LogError("result = %s", ENUM_TO_STRING(IOTHUB_CLIENT_RESULT, result))
```

but I do not see any additional lines on the Serial Monitor:

> dhcp client start...
> ip:192.168.3.111,mask:255.255.255.0,gw:192.168.3.1
> Connected to wifi
> please start sntp first !
> Fetching NTP epoch time failed! Waiting 2 seconds to retry.
> please start sntp first !
> Fetching NTP epoch time failed! Waiting 2 seconds to retry.
> Thu Jan 05 20:32:47 2017
> 
> Fetched NTP epoch time is: 1483648368
> IoT Hub SDK for C, version 1.0.17
> result = IOTHUB_CLIENT_OK
> IoTHubClient accepted the message for delivery.
> TLS failed to start the connection process.
> Error: io_open failed
> failure connecting to address ih-demos.azure-devices.net:0.
> Evaluated delay 0 at 1 attempt to retry
> 
> TLS failed to start the connection process.
> Error: io_open failed
> failure connecting to address ih-demos.azure-devices.net:0.
> Evaluated delay 0 at 2 attempt to retry
> 
> TLS failed to start the connection process.
> Error: io_open failed
> failure connecting to address ih-demos.azure-devices.net:0.
> Evaluated delay 1 at 3 attempt to retry

**Comment by mamokarz** [comment]
I’m running the same sample here, and the log result is

```
->  CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: %zu | USERNAME: MokaSuite.azure-devices.net/Huzzah_w_DHT22/api-version=2016-11-14&DeviceClientType=iothubclient%2F1.0.17 | PWD: XXXX | CLEAN: 0
<-  CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
->  SUBSCRIBE | PACKET_ID: 7 | TOPIC_NAME: devices/Huzzah_w_DHT22/messages/devicebound/# | QOS: 1
<-  SUBACK | PACKET_ID: 7 | RETURN_CODE: 1
->  PINGREQ
<-  PINGRESP   …
```

**Comment by mamokarz** [comment]
I’m wondering if we are running in some contamination problem. Sometimes, the Arduino IDE do not recognize changes in the library and just reuse parts of the previous compilation. To avoid it, can you please totally delete the previous result? It is located in a temporary directory with the name arduino_build_#####

```
C:\Users\ <<userName>> \AppData\Local\Temp\arduino_build_####
```

You will find `simplesample_mqtt.ino.bin` inside of it. Delete all files and directories inside of this arduino_build_#### directory. Recompile the code and check if this directory was populated again.

**Comment by jorupp** [comment]
Maybe the Azure IoT hubs in different regions/subs are behaving differently on this?  I can't get MokaSuite.azure-devices.net to resolve to try it with my device, but I get the same TLS failure on ih-demos.azure-devices.net port 8883 that I do on the one I'm testing with (pourcast.azure-devices.net).

@mamokarz - could you try pointing the WiFiSSLClient test app at both your IoT hub and ours on port 8883 and see if you get the same behavior (connect.client(server, 8883) returning false)?

**Comment by astaykov** [comment]
If someone can tell me what it is ....
I updated **all boards** and **all updatable libraries** on my Arduino IDE 1.6.12 and suddenly it all works, with the exception - all blows out by sending Cloud-to-Device messages for commands (i.e. TurnFanOn):

> dhcp client start...
> ip:192.168.3.111,mask:255.255.255.0,gw:192.168.3.1
> Connected to wifi
> please start sntp first !
> Fetching NTP epoch time failed! Waiting 2 seconds to retry.
> Thu Jan 05 22:07:53 2017
> 
> Fetched NTP epoch time is: 1483654074
> IoT Hub SDK for C, version 1.0.17
> result = IOTHUB_CLIENT_OK
> IoTHubClient accepted the message for delivery.
> ->  CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: %zu | USERNAME: ih-demos.azure-devices.net/brandnew/api-version=2016-11-14&DeviceClientType=iothubclient%2F1.0.17 | PWD: XXXX | CLEAN: 0
> <-  CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x0
> ->  SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/brandnew/messages/devicebound/# | QOS: 1
> <-  SUBACK | PACKET_ID: 2 | RETURN_CODE: 1
> ->  PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/brandnew/messages/events/ | PACKET_ID: 3 | PAYLOAD_LEN: %zu
> <-  PUBACK | PACKET_ID: 3
> Message Id: 1 Received.
> Result Call Back Called! Result is: IOTHUB_CLIENT_CONFIRMATION_OK 
> <-  PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE = 0x01 | TOPIC_NAME: devices/brandnew/messages/devicebound/%24.mid=d1d2f668-563c-4798-baf2-f7156efa8a8b&%24.to=%2Fdevices%2Fbrandnew%2Fmessages%2FdeviceBound&iothub-ack=full | PACKET_ID: 6 | PAYLOAD_LEN: %zu
> Fatal exception 28(LoadProhibitedCause):
> epc1=0x40207752, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000025, depc=0x00000000
> 
> Exception (28):
> epc1=0x40207752 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000025 depc=0x00000000
> 
> ctx: cont 
> sp: 3fff33d0 end: 3fff3840 offset: 01a0
> 
> >>>stack>>>
> 3fff3570:  3fff3590 402100e5 3fff821c 3fff821c  
> 3fff3580:  3fff7b2c 3fff7b2c 3fff528c 40210040  
> 3fff3590:  3fff27c0 00000815 00000815 4010020c  
> 3fff35a0:  3fff7b2c 3fff821c 3fff821c 4010068c  
> 3fff35b0:  00000000 3fff821c 3fff53e4 00000006  
> 3fff35c0:  3fff7b2c 3fff821c 3fff53e4 40210660  
> 3fff35d0:  7575d1c5 00000000 00000000 3fff3560  
> 3fff35e0:  3fff94f0 00000017 00000010 4010606a  
> 3fff35f0:  3fff57bc 00000001 00000028 00000000  
> 3fff3600:  00000000 00000001 3fff9456 3fff26dc  
> 3fff3610:  3fff5300 3fff517c 4021500c 00000000  
> 3fff3620:  3fff5454 00000000 3fff5454 4021107d  
> 3fff3630:  3fff5454 00000000 00000046 40211bdc  
> 3fff3640:  3fff3680 00000047 0000007d 4021451a  
> 3fff3650:  3fff3680 00000080 00000000 3fff517c  
> 3fff3660:  3fff5300 00000000 3fff53e4 4020fff3  
> 3fff3670:  3fff53e4 3fff821c 3fff55fc 4020c100  
> 3fff3680:  65644632 65636976 6e756f42 6f692664  
> 3fff3690:  62756874 6b63612d 6c75663d 7b06006c  
> 3fff36a0:  6d614e22 3a202265 75542220 61466e72  
> 3fff36b0:  226e4f6e 6150222c 656d6172 73726574  
> 3fff36c0:  203a2022 617d7d7b 662d3266 36353137  
> 3fff36d0:  38616665 26623861 2e343225 253d6f74  
> 3fff36e0:  65644632 65636976 46322573 6e617262  
> 3fff36f0:  77656e64 00b64000 00000000 40212698  
> 3fff3700:  00000000 3fff5444 3fff53e4 40213374  
> 3fff3710:  3fff5300 00b64000 00000000 40210f97  
> 3fff3720:  00000000 3fff5314 3fff3740 3fff280c  
> 3fff3730:  3fff5300 00000000 3fff528c 40208ed4  
> 3fff3740:  000061a8 00000001 00000000 3fff54ac  
> 3fff3750:  3fff57c4 000000f0 00000001 00000000  
> 3fff3760:  00000bb8 3fff37d0 3fff37d0 3ffebb16  
> 3fff3770:  3fff5300 3fff517c 3fff517c 3ffe95b0  
> 3fff3780:  3fff280c 3fff5694 00000008 00000000  
> 3fff3790:  00000000 00b64000 00000000 3fff280c  
> 3fff37a0:  3fff5184 3fff517c 3fff517c 402091f0  
> 3fff37b0:  3ffe95b0 3fff517c 3fff517c 40205fc4  
> 3fff37c0:  000061a8 3fff280c 4021500c 3fff2820  
> 3fff37d0:  3fff5184 00000064 00000064 40211d7f  
> 3fff37e0:  3ffe95b0 3fff517c 3fff55dc 3fff280c  
> 3fff37f0:  3ffe95b0 3fff517c 3fff55dc 40201348  
> 3fff3800:  0000002c 3fff57a4 3fff2701 402135d9  
> 3fff3810:  3fffdad0 00000000 3fff2804 402134a8  
> 3fff3820:  feefeffe feefeffe feefeffe 40215058  
> 3fff3830:  feefeffe feefeffe 3fff2820 40100718  
> <<<stack<<<
> 
>  ets Jan  8 2013,rst cause:2, boot mode:(1,6)
> 
> 
>  ets Jan  8 2013,rst cause:4, boot mode:(1,6)
> 
> wdt reset
> 

What a game ...

**Comment by mamokarz** [comment]
Great!

This is a knowing bug, I'll give you a workaround.

**Comment by mamokarz** [comment]
It is related with the `toupper` and `isdigit` for some Arduinos. To fix it, create the follow macro on `iothubtransport_mqtt_common.c` and replace all `toupper` on this file to `TOUPPER`.

```c
#define TOUPPER(c)      (((c>='a') && (c<='z'))?c-'a'+'A':c)
```

Do the same for the `isdigit` in the `jsondecoder.c` defining the new `ISDIGIT` using the macro

```c
#define ISDIGIT(c)      (((c>='0') && (c<='9'))?1:0)
```

**Comment by mamokarz** [comment]
jorupp, I didn't understand what you asked for. Please try MokaFeatherM0Suite.azure-devices.net

**Comment by jorupp** [comment]
Looks like my issue (and the one at https://github.com/Azure-Samples/iot-hub-c-m0wifi-getstartedkit/issues/44) aren't the same as this one then (since you quit getting the io_open errors after updating everything) - sorry for introducing confusion :(

**Comment by astaykov** [comment]
@mamokarz - after updating all libraries and boards (frankly, the libraries that were update-able had at first sight nothing to do with this - i.e. Firmata and 2 more had new versions) and tweaking the source with your workaround now everything seems to work perfectly!
Thanks and sorry troubles!

> dhcp client start...
> ip:192.168.3.104,mask:255.255.255.0,gw:192.168.3.1
> Connected to wifi
> please start sntp first !
> Fetching NTP epoch time failed! Waiting 2 seconds to retry.
> Fri Jan 06 19:53:02 2017
> 
> Fetched NTP epoch time is: 1483732383
> IoT Hub SDK for C, version 1.0.17
> result = IOTHUB_CLIENT_OK
> IoTHubClient accepted the message for delivery.
> ->  CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: %zu | USERNAME: ih-demos.azure-devices.net/brandnew/api-version=2016-11-14&DeviceClientType=iothubclient%2F1.0.17 | PWD: XXXX | CLEAN: 0
> <-  CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
> ->  SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: devices/brandnew/messages/devicebound/# | QOS: 1
> <-  SUBACK | PACKET_ID: 2 | RETURN_CODE: 1
> ->  PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE | TOPIC_NAME: devices/brandnew/messages/events/ | PACKET_ID: 3 | PAYLOAD_LEN: %zu
> <-  PUBACK | PACKET_ID: 3
> Message Id: 1 Received.
> Result Call Back Called! Result is: IOTHUB_CLIENT_CONFIRMATION_OK 
> <-  PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE = 0x01 | TOPIC_NAME: devices/brandnew/messages/devicebound/%24.mid=7cf05eda-4688-4029-bcbf-c9aa61296a71&%24.to=%2Fdevices%2Fbrandnew%2Fmessages%2FdeviceBound&iothub-ack=full | PACKET_ID: 7 | PAYLOAD_LEN: %zu
> Turning fan on.
> <-  PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_LEAST_ONCE = 0x01 | TOPIC_NAME: devices/brandnew/messages/devicebound/%24.mid=ae6177b5-5723-4d70-b15b-fac200ea7628&%24.to=%2Fdevices%2Fbrandnew%2Fmessages%2FdeviceBound&iothub-ack=full | PACKET_ID: 8 | PAYLOAD_LEN: %zu
> Setting Air Resistance Position to 20.
>

**Comment by jamesguitar3** [comment]
I am running into this same error "io_open failed" with NodeMCU V2.0 after updated the libraries. Any thoughts? Thanks.
AzureIoTHub-V1.0.30
AzureIoTProtocol_HTTP - 1.0.30
AzureIoTProtocol_MQTT - 1.0.30
AzureIoTUtility - 1.0.30
esp8266 - 2.2.0

**Comment by mysaggar** [comment]
Hi @astaykov could you explain your solution and also point out the process you followed, I have run into a similar error.
I followed [https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-arduino-huzzah-esp8266-get-started](url) and tried working with 2 boards, Adafruit Feather Huzzah Esp8266 and NodeMCU V2.0. 
The error I am getting is `connected with Moriarty, channel 11
dhcp client start...
ip:192.168.43.126,mask:255.255.255.0,gw:192.168.43.1
Connected to wifi Moriarty.
Fetched NTP epoch time is: 28812.
result = IOTHUB_CLIENT_OK
Sending message: {"deviceId":"Feather HUZZAH ESP8266 WiFi","messageId":1,"temperature":25,"humidity":32}.
IoTHubClient accepted the message for delivery.
TLS failed to start the connection process.
Error: io_open failed
failure connecting to address iotpra2.azure-devices.net.
TLS failed to start the connection process.
Error: io_open failed
failure connecting to address iotpra2.azure-devices.net.
TLS failed to start the connection process.
Error: io_open failed
failure connecting to address iotpra2.azure-devices.net.
TLS failed to start the connection process.
Error: io_open failed
failure connecting to address iotpra2.azure-devices.net.`

Is there a workaround for this ?
or could you detail out the changes you made to your code?
Thanks In advance

Also including @mamokarz If you have any insight into this?

**Comment by sk1tt1sh** [comment]
@mysaggar Here's the method I used to resolve the TLS error:

1. Make sure you have Arduino IDE version 1.8 or newer
2. Install ESP Board Manager 2.4.0 <--------------**This appears to be the key. >V2.4 doesn't seem to work...???**
3. Install Azure IoT libraries 1.0.45 for every version (Azure IoT Utility/Client_MQTT/Hub)

I find that if you're using "iot-hub-feather-huzzah-client-app" and you restart the device you will need to put in a bunk wifi config, reset, then re-input your configs. There's some code bugs that can fixed in that but it appears they don't support pull requests for whatever reason.

**Comment by Elgaatoo** [comment]
@sk1tt1sh could you please explain what you mean by bunk WiFi config. I tried reseting my Huzzah ESP8266 and typing in the same right WiFi credentials. I am still getting this TLS error which @mysaggar got.
I'm using:
Board - ESP8266 2.4.0
Azureiothub 1.0.45
azureiotprotocol_mqtt 1.0.45
azureiotutility 1.0.45
arduinoJson 5.13.4.
DHT Sensor Library (for DHT11) 1.3.4
on Arduino 1.8.9.

**Comment by sk1tt1sh** [comment]
@Elgaatoo I mean just a non-existant wifi ssid & password to overwrite the stored values. 

If you're still receiving the TLS error it means that the project is building with the new Bear SSL libs. You may need to ensure that dependencies are not targeting >2.4.x version of ESP822 Arduino, I know in Visual Studio Code I had to manually remove the path reference as you may have multiple versions of the same library. What are you using for a development environment?

**Comment by Elgaatoo** [comment]
@sk1tt1sh, I overwrote the credentials and then typed the right ones. I am still getting the TLS error. Visual Studio and tried it also on Arduino.

**Comment by Elgaatoo** [comment]
Hi, I managed to fix the problem. Thx. :)
